---
name: Manual website deployment
on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          fetch-depth: 0 # fetch all commits and branches for mike to work properly
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: 3.x
      - name: Tools setup
        run: |
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"
          sudo snap install yq
          cd documentation
          pip install mkdocs-material
          pip install mike
      - name: Render docs and publish
        run: |
          export PROJECT_VERSION=$(cat .github/project.yml | yq eval '.release.current-version' -)
          cd documentation
          mike deploy --push --update-aliases $PROJECT_VERSION latest
          mike set-default --push latest
