name: JReleaser
run-name: Use JReleaser for the ${{github.event.inputs.tag || github.ref_name}} release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jreleaser:
    name: JReleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Call JReleaser
        env:
          GH_TOKEN: ${{ github.token }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{github.event.inputs.tag || github.ref_name}}
          JRELEASER_TAG_NAME: ${{github.event.inputs.tag || github.ref_name}}
        run: |
          sudo snap install yq
          export JRELEASER_PREVIOUS_TAG_NAME=$(gh release list --json isLatest,tagName --jq '.[] | select(.isLatest)|.tagName')
          ./mvnw --batch-mode --no-transfer-progress -Pjreleaser jreleaser:full-release -pl :mutiny-project