name: SmallRye Release
run-name: Perform ${{github.event.inputs.tag || github.ref_name}} Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  attestations: write
  id-token: write
  # Needed for the publish-* workflows
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: smallrye/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}

  jreleaser:
    name: JReleaser
    runs-on: ubuntu-latest
    needs: perform-release
    steps:
      - uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Call JReleaser
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{github.event.inputs.tag || github.ref_name}}
          JRELEASER_TAG_NAME: ${{github.event.inputs.tag || github.ref_name}}
        run: |
          sudo snap install yq
          export JRELEASER_PREVIOUS_TAG_NAME=$(gh release list --json isLatest,tagName --jq '.[] | select(.isLatest)|.tagName')
          ./mvnw --batch-mode --no-transfer-progress -Pjreleaser jreleaser:full-release -pl :mutiny-project